## 절대 모멘텀
- 전년도(3개월, 6개월 12개월)의 수정주가와 전월의 수정주가를 이용하여 구매의 타이밍을 잡는 투자 전략
- 구매 신호 -> (전월의 수정 주가 / 전년도의 수정 주가) - 1 값이 0보다 크고 무한대가 아닌 경우

1. 파생변수 STD-YM 생성 : index에서 년-월을 추출하여 대입
2. STD-YM별 마지막날의 데이터들을 모아서 month_last_df 데이터 프레임을 생성
3. 전월의 수정주가 파생변수 생성 -> 전월 수정 주가 대입
4. 전년도의 수정주가 파생변수 생성 -> 전년도 수정 주가 대입
5. 구매 신호를 생성
6. 원본의 데이터에서 구호 신호에 따른 거래 내역 생성
7. 수익을 계산

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
df=pd.read_csv('../../csv/AMZN.csv', index_col='Date')
df.head()

                Open      High       Low     Close  Adj Close    Volume
Date
1997-05-15  2.437500  2.500000  1.927083  1.958333   1.958333  72156000
1997-05-16  1.968750  1.979167  1.708333  1.729167   1.729167  14700000
1997-05-19  1.760417  1.770833  1.625000  1.708333   1.708333   6106800
1997-05-20  1.729167  1.750000  1.635417  1.635417   1.635417   5467200
1997-05-21  1.635417  1.645833  1.375000  1.427083   1.427083  18853200

In [3]:
#index 데이터 시계열로 변환
df.index=pd.to_datetime(df.index)

In [4]:
#index 데이터에서 년-월을 추출하여 STD-YM에 대입
df.index.strftime('%Y-%m')

Index(['1997-05', '1997-05', '1997-05', '1997-05', '1997-05', '1997-05',
       '1997-05', '1997-05', '1997-05', '1997-05',
       ...
       '2019-06', '2019-06', '2019-06', '2019-06', '2019-06', '2019-06',
       '2019-06', '2019-06', '2019-06', '2019-06'],
      dtype='object', name='Date', length=5563)

In [ ]:
ym_list=[]

for idx in df.index:
    ym=idx.strftime('%Y-%m')
    ym_list.append(ym)

ym_list

In [6]:
df['STD-YM']=ym_list

In [7]:
df.loc['1997-05-25' : '1991-06-05', ]

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume, STD-YM]
Index: []

In [8]:
#현재 행의 STD-YM과 다음 행의 STD-YM이 다른 경우 : 월말
flag=df['STD-YM'] != df.shift(-1)['STD-YM']
df.loc[flag,]

,Open,High,Low,Close,Adj Close,Volume,STD-YM
Date,,,,,,,
1997-05-30,1.500000,1.510417,1.479167,1.500000,1.500000,2594400,1997-05
1997-06-30,1.510417,1.598958,1.479167,1.541667,1.541667,2746800,1997-06
1997-07-31,2.437500,2.437500,2.333333,2.395833,2.395833,1454400,1997-07
1997-08-29,2.364583,2.375000,2.322917,2.338542,2.338542,722400,1997-08
1997-09-30,4.000000,4.348958,3.802083,4.338542,4.338542,5254800,1997-09
...,...,...,...,...,...,...,...
2019-02-28,1635.250000,1651.770020,1633.829956,1639.829956,1639.829956,3025900,2019-02
2019-03-29,1786.579956,1792.859985,1776.630005,1780.750000,1780.750000,3320800,2019-03
2019-04-30,1930.099976,1935.709961,1906.949951,1926.520020,1926.520020,3506000,2019-04
2019-05-31,1790.010010,1795.589966,1772.699951,1775.069946,1775.069946,4618800,2019-05
2019-06-24,1912.660034,1916.859985,1901.329956,1907.953857,1907.953857,1243601,2019-06

In [9]:
#그룹화를 하고 마지막 데이터만 확인
month_last_df=df.groupby('STD-YM').tail(1)

In [10]:
#전월의 수정주가, 전년도의 수정주가 컬럼을 생성
month_last_df['BF-1M']=month_last_df.shift(1)['Adj Close'].fillna(0)
month_last_df['BF-12M']=month_last_df.shift(12)['Adj Close'].fillna(0)

month_last_df.iloc[10:15, ]

C:\Users\user\AppData\Local\Temp\ipykernel_19092\706146360.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  month_last_df['BF-1M']=month_last_df.shift(1)['Adj Close'].fillna(0)
C:\Users\user\AppData\Local\Temp\ipykernel_19092\706146360.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  month_last_df['BF-12M']=month_last_df.shift(12)['Adj Close'].fillna(0)

,Open,High,Low,Close,Adj Close,Volume,STD-YM,BF-1M,BF-12M
Date,,,,,,,,,
1998-03-31,7.114583,7.208333,6.979167,7.127600,7.127600,6565200,1998-03,6.416667,0.000000
1998-04-30,8.125000,8.166667,7.541667,7.645833,7.645833,22485600,1998-04,7.127600,0.000000
1998-05-29,7.156250,7.416667,7.125000,7.343750,7.343750,8641200,1998-05,7.645833,1.500000
1998-06-30,16.302084,16.916666,16.125000,16.625000,16.625000,21877200,1998-06,7.343750,1.541667
1998-07-31,19.083334,19.187500,18.187500,18.479166,18.479166,13440600,1998-07,16.625000,2.395833

In [13]:
#거래내역 추가 (_df, month_last_df)
#거래내역은 df에 추가
#month_last_df는 구매 신호(momentum_index)를 확인하기 위해 사용
for i in month_last_df.index:
    signal=''

    #절대 모멘텀의 계산식 : 전월 수정 주가 / 전년도 수정 주가 - 1
    momentum_index=month_last_df.loc[i,'BF-1M'] / month_last_df.loc[i,'BF-12M'] - 1
    #0보다 크고 무한대가 아닌 경우 : 구매 신호
    flag = (momentum_index > 0) & (momentum_index != np.inf)
    if flag:
        signal='buy'
    
    print(f'날짜 : {i}, 모멘텀 인덱스 : {momentum_index}, signal : {signal}')
    df.loc[i:,'trade']=signal

C:\Users\user\AppData\Local\Temp\ipykernel_19092\2645774783.py:8: RuntimeWarning: invalid value encountered in scalar divide
  momentum_index=month_last_df.loc[i,'BF-1M'] / month_last_df.loc[i,'BF-12M'] - 1
C:\Users\user\AppData\Local\Temp\ipykernel_19092\2645774783.py:8: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=month_last_df.loc[i,'BF-1M'] / month_last_df.loc[i,'BF-12M'] - 1
C:\Users\user\AppData\Local\Temp\ipykernel_19092\2645774783.py:8: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=month_last_df.loc[i,'BF-1M'] / month_last_df.loc[i,'BF-12M'] - 1
C:\Users\user\AppData\Local\Temp\ipykernel_19092\2645774783.py:8: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=month_last_df.loc[i,'BF-1M'] / month_last_df.loc[i,'BF-12M'] - 1
C:\Users\user\AppData\Local\Temp\ipykernel_19092\2645774783.py:8: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=month_last_df.loc[i,'BF-1M'] / month_last_df.loc[i,'BF-12M'] - 1
C:\Users\user\AppData\Local\Temp\ipykernel_19092\2645774783.py:8: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=month_last_df.loc[i,'BF-1M'] / month_last_df.loc[i,'BF-12M'] - 1
C:\Users\user\AppData\Local\Temp\ipykernel_19092\2645774783.py:8: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=month_last_df.loc[i,'BF-1M'] / month_last_df.loc[i,'BF-12M'] - 1
C:\Users\user\AppData\Local\Temp\ipykernel_19092\2645774783.py:8: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=month_last_df.loc[i,'BF-1M'] / month_last_df.loc[i,'BF-12M'] - 1
C:\Users\user\AppData\Local\Temp\ipykernel_19092\2645774783.py:8: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=month_last_df.loc[i,'BF-1M'] / month_last_df.loc[i,'BF-12M'] - 1
C:\Users\user\AppData\Local\Temp\ipykernel_19092\2645774783.py:8: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=month_last_df.loc[i,'BF-1M'] / month_last_df.loc[i,'BF-12M'] - 1
C:\Users\user\AppData\Local\Temp\ipykernel_19092\2645774783.py:8: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=month_last_df.loc[i,'BF-1M'] / month_last_df.loc[i,'BF-12M'] - 1
C:\Users\user\AppData\Local\Temp\ipykernel_19092\2645774783.py:8: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=month_last_df.loc[i,'BF-1M'] / month_last_df.loc[i,'BF-12M'] - 1

날짜 : 1997-05-30 00:00:00, 모멘텀 인덱스 : nan, signal :
날짜 : 1997-06-30 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 1997-07-31 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 1997-08-29 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 1997-09-30 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 1997-10-31 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 1997-11-28 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 1997-12-31 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 1998-01-30 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 1998-02-27 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 1998-03-31 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 1998-04-30 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 1998-05-29 00:00:00, 모멘텀 인덱스 : 4.0972219999999995, signal : buy
날짜 : 1998-06-30 00:00:00, 모멘텀 인덱스 : 3.7635124835648686, signal : buy
날짜 : 1998-07-31 00:00:00, 모멘텀 인덱스 : 5.9391314002269775, signal : buy
날짜 : 1998-08-31 00:00:00, 모멘텀 인덱스 : 6.902003042921615, signal : buy
날짜 : 1998-09-30 00:00:00, 모멘텀 인덱스 : 2.217286590748689, signal : buy
날짜 : 1998-10-30 00:00:00, 모멘텀 인덱스 : 2.659836174415487, signal : buy
날짜 : 1998-11-30 00:00:00, 모멘텀 인덱스 : 4.108585696969697, signal : buy
날짜 : 1998-12-31 00:00:00, 모멘텀 인덱스 : 5.373444406535729, signal : buy
날짜 : 1999-01-29 00:00:00, 모멘텀 인덱스 : 9.889830041367455, signal : buy
날짜 : 1999-02-26 00:00:00, 모멘텀 인덱스 : 8.112012513661687, signal : buy
날짜 : 1999-03-31 00:00:00, 모멘텀 인덱스 : 7.9879482574779725, signal : buy
날짜 : 1999-04-30 00:00:00, 모멘텀 인덱스 : 10.260218474559935, signal : buy
날짜 : 1999-05-28 00:00:00, 모멘텀 인덱스 : 10.714893617021277, signal : buy
날짜 : 1999-06-30 00:00:00, 모멘텀 인덱스 : 2.5714285714285716, signal : buy
날짜 : 1999-07-30 00:00:00, 모멘텀 인덱스 : 2.385569456976576, signal : buy
날짜 : 1999-08-31 00:00:00, 모멘텀 인덱스 : 2.5843284438048584, signal : buy
날짜 : 1999-09-30 00:00:00, 모멘텀 인덱스 : 2.3426652933541874, signal : buy
날짜 : 1999-10-29 00:00:00, 모멘텀 인덱스 : 2.7933762940069613, signal : buy
날짜 : 1999-11-30 00:00:00, 모멘텀 인덱스 : 1.20703125, signal : buy
날짜 : 1999-12-31 00:00:00, 모멘텀 인덱스 : 0.5887159137440394, signal : buy
날짜 : 2000-01-31 00:00:00, 모멘텀 인덱스 : 0.3019775521111705, signal : buy
날짜 : 2000-02-29 00:00:00, 모멘텀 인덱스 : 0.007804878048780495, signal : buy
날짜 : 2000-03-31 00:00:00, 모멘텀 인덱스 : -0.19999999999999996, signal :
날짜 : 2000-04-28 00:00:00, 모멘텀 인덱스 : -0.22121322193970216, signal :
날짜 : 2000-05-31 00:00:00, 모멘텀 인덱스 : -0.07052631578947366, signal :
날짜 : 2000-06-30 00:00:00, 모멘텀 인덱스 : -0.22777222777222772, signal :
날짜 : 2000-07-31 00:00:00, 모멘텀 인덱스 : -0.27420362273579013, signal :
날짜 : 2000-08-31 00:00:00, 모멘텀 인덱스 : -0.5155778894472363, signal :
날짜 : 2000-09-29 00:00:00, 모멘텀 인덱스 : -0.48084440969507425, signal :
날짜 : 2000-10-31 00:00:00, 모멘텀 인덱스 : -0.4557522123893806, signal :
날짜 : 2000-11-30 00:00:00, 모멘텀 인덱스 : -0.5694342395297576, signal :
날짜 : 2000-12-29 00:00:00, 모멘텀 인덱스 : -0.6756978653530378, signal :
날짜 : 2001-01-31 00:00:00, 모멘텀 인덱스 : -0.7589545014520813, signal :
날짜 : 2001-02-28 00:00:00, 모멘텀 인덱스 : -0.7486388384754992, signal :
날짜 : 2001-03-30 00:00:00, 모멘텀 인덱스 : -0.8479477611940298, signal :
날짜 : 2001-04-30 00:00:00, 모멘텀 인덱스 : -0.8146319365798415, signal :
날짜 : 2001-05-31 00:00:00, 모멘텀 인덱스 : -0.6733764553686934, signal :
날짜 : 2001-06-29 00:00:00, 모멘텀 인덱스 : -0.5403786299483649, signal :
날짜 : 2001-07-31 00:00:00, 모멘텀 인덱스 : -0.5302904564315353, signal :
날짜 : 2001-08-31 00:00:00, 모멘텀 인덱스 : -0.6990361445783133, signal :
날짜 : 2001-09-28 00:00:00, 모멘텀 인덱스 : -0.7674146341463415, signal :
날짜 : 2001-10-31 00:00:00, 모멘텀 인덱스 : -0.8369965870307168, signal :
날짜 : 2001-11-30 00:00:00, 모멘텀 인덱스 : -0.7172658227848101, signal :
날짜 : 2001-12-31 00:00:00, 모멘텀 인덱스 : -0.2726104417670683, signal :
날짜 : 2002-01-31 00:00:00, 모멘텀 인덱스 : -0.37501805054151627, signal :
날짜 : 2002-02-28 00:00:00, 모멘텀 인덱스 : 0.3928834355828221, signal : buy
날짜 : 2002-03-28 00:00:00, 모멘텀 인덱스 : 0.378299120234604, signal : buy
날짜 : 2002-04-30 00:00:00, 모멘텀 인덱스 : -0.09378960709759177, signal :
날짜 : 2002-05-31 00:00:00, 모멘텀 인덱스 : 0.0, signal :
날짜 : 2002-06-28 00:00:00, 모멘텀 인덱스 : 0.2883392226148409, signal : buy
날짜 : 2002-07-31 00:00:00, 모멘텀 인덱스 : 0.3010408326661329, signal : buy
날짜 : 2002-08-30 00:00:00, 모멘텀 인덱스 : 0.616331096196868, signal : buy
날짜 : 2002-09-30 00:00:00, 모멘텀 인덱스 : 1.5025125628140703, signal : buy
날짜 : 2002-10-31 00:00:00, 모멘텀 인덱스 : 1.2822349570200573, signal : buy
날짜 : 2002-11-29 00:00:00, 모멘텀 인덱스 : 0.7102474381625441, signal : buy
날짜 : 2002-12-31 00:00:00, 모멘텀 인덱스 : 1.1580406654343807, signal : buy
날짜 : 2003-01-31 00:00:00, 모멘텀 인덱스 : 0.3312190979563072, signal : buy
날짜 : 2003-02-28 00:00:00, 모멘텀 인덱스 : 0.5496453900709222, signal : buy
날짜 : 2003-03-31 00:00:00, 모멘텀 인덱스 : 0.5391608391608391, signal : buy
날짜 : 2003-04-30 00:00:00, 모멘텀 인덱스 : 0.5596165033183642, signal : buy
날짜 : 2003-05-30 00:00:00, 모멘텀 인덱스 : 0.5737795392210641, signal : buy
날짜 : 2003-06-30 00:00:00, 모멘텀 인덱스 : 1.2086153230769234, signal : buy
날짜 : 2003-07-31 00:00:00, 모멘텀 인덱스 : 1.5134948096885816, signal : buy
날짜 : 2003-08-29 00:00:00, 모멘텀 인덱스 : 1.7871485274431063, signal : buy
날짜 : 2003-09-30 00:00:00, 모멘텀 인덱스 : 1.9077212806026367, signal : buy
날짜 : 2003-10-31 00:00:00, 모멘텀 인덱스 : 1.501549457564594, signal : buy
날짜 : 2003-11-28 00:00:00, 모멘텀 인덱스 : 1.3310492505353317, signal : buy
날짜 : 2003-12-31 00:00:00, 모멘텀 인덱스 : 1.85706743552501, signal : buy
날짜 : 2004-01-30 00:00:00, 모멘텀 인덱스 : 1.4082379405034322, signal : buy
날짜 : 2004-02-27 00:00:00, 모멘텀 인덱스 : 1.2898683325761016, signal : buy
날짜 : 2004-03-31 00:00:00, 모멘텀 인덱스 : 0.6523241009479794, signal : buy
날짜 : 2004-04-30 00:00:00, 모멘텀 인덱스 : 0.5085394733865642, signal : buy
날짜 : 2004-05-28 00:00:00, 모멘텀 인덱스 : 0.21482304861585533, signal : buy
날짜 : 2004-06-30 00:00:00, 모멘텀 인덱스 : 0.3353524229074889, signal : buy
날짜 : 2004-07-30 00:00:00, 모멘텀 인덱스 : 0.3064361985215225, signal : buy
날짜 : 2004-08-31 00:00:00, 모멘텀 인덱스 : -0.15975824697754748, signal :
날짜 : 2004-09-30 00:00:00, 모멘텀 인덱스 : -0.21247162915548212, signal :
날짜 : 2004-10-29 00:00:00, 모멘텀 인덱스 : -0.24931102333272093, signal :
날짜 : 2004-11-30 00:00:00, 모멘텀 인덱스 : -0.3676116292827195, signal :
날짜 : 2004-12-31 00:00:00, 모멘텀 인덱스 : -0.24591408677145743, signal :
날짜 : 2005-01-31 00:00:00, 모멘텀 인덱스 : -0.12123017376070744, signal :
날짜 : 2005-02-28 00:00:00, 모멘텀 인덱스 : 0.0048826554235132935, signal : buy
날짜 : 2005-03-31 00:00:00, 모멘텀 인덱스 : -0.18715340081223197, signal :
날짜 : 2005-04-29 00:00:00, 모멘텀 인덱스 : -0.21399078963260498, signal :
날짜 : 2005-05-31 00:00:00, 모멘텀 인덱스 : -0.33278348453608253, signal :
날짜 : 2005-06-30 00:00:00, 모멘텀 인덱스 : -0.3472427078219592, signal :
날짜 : 2005-07-29 00:00:00, 모멘텀 인덱스 : -0.14979440646425513, signal :
날짜 : 2005-08-31 00:00:00, 모멘텀 인덱스 : 0.18379662254317308, signal : buy
날짜 : 2005-09-30 00:00:00, 모멘텀 인덱스 : 0.04503181485482588, signal : buy
날짜 : 2005-10-31 00:00:00, 모멘텀 인덱스 : 0.32727798630887817, signal : buy
날짜 : 2005-11-30 00:00:00, 모멘텀 인덱스 : 0.004536315524193535, signal : buy
날짜 : 2005-12-30 00:00:00, 모멘텀 인덱스 : 0.09415213153867419, signal : buy
날짜 : 2006-01-31 00:00:00, 모멘텀 인덱스 : 0.09093014597570215, signal : buy
날짜 : 2006-02-28 00:00:00, 모멘텀 인덱스 : 0.27401932916429783, signal : buy
날짜 : 2006-03-31 00:00:00, 모멘텀 인덱스 : 0.09250070032098034, signal : buy
날짜 : 2006-04-28 00:00:00, 모멘텀 인덱스 : 0.1288627277854535, signal : buy
날짜 : 2006-05-31 00:00:00, 모멘텀 인덱스 : -0.008448296730402483, signal :
날짜 : 2006-06-30 00:00:00, 모멘텀 인덱스 : 0.04593535811423366, signal : buy
날짜 : 2006-07-31 00:00:00, 모멘텀 인덱스 : -0.14330014869102337, signal :
날짜 : 2006-08-31 00:00:00, 모멘텀 인덱스 : -0.37025764940848593, signal :
날짜 : 2006-09-29 00:00:00, 모멘텀 인덱스 : -0.3194260335414135, signal :
날짜 : 2006-10-31 00:00:00, 모멘텀 인덱스 : -0.19417967400452396, signal :
날짜 : 2006-11-30 00:00:00, 모멘텀 인덱스 : -0.21399090412692745, signal :
날짜 : 2006-12-29 00:00:00, 모멘텀 인덱스 : -0.14443269800921743, signal :
날짜 : 2007-01-31 00:00:00, 모멘텀 인덱스 : -0.11958949129852736, signal :
날짜 : 2007-02-28 00:00:00, 모멘텀 인덱스 : 0.006143135847840098, signal : buy
날짜 : 2007-03-30 00:00:00, 모멘텀 인덱스 : 0.0714481267847833, signal : buy
날짜 : 2007-04-30 00:00:00, 모멘텀 인덱스 : 0.13007674325693652, signal : buy
날짜 : 2007-05-31 00:00:00, 모멘텀 인덱스 : 0.7720312114408783, signal : buy
날짜 : 2007-06-29 00:00:00, 모멘텀 인덱스 : 0.7874870475698037, signal : buy
날짜 : 2007-07-31 00:00:00, 모멘텀 인덱스 : 1.5440686702889055, signal : buy
날짜 : 2007-08-31 00:00:00, 모멘텀 인덱스 : 1.547518683100876, signal : buy
날짜 : 2007-09-28 00:00:00, 모멘텀 인덱스 : 1.4878582343666946, signal : buy
날짜 : 2007-10-31 00:00:00, 모멘텀 인덱스 : 1.445523812024153, signal : buy
날짜 : 2007-11-30 00:00:00, 모멘텀 인덱스 : 1.209965344571145, signal : buy
날짜 : 2007-12-31 00:00:00, 모멘텀 인덱스 : 1.2949822679924545, signal : buy
날짜 : 2008-01-31 00:00:00, 모멘텀 인덱스 : 1.4592514977038227, signal : buy
날짜 : 2008-02-29 00:00:00, 모멘텀 인덱스 : 0.9851813741742812, signal : buy
날짜 : 2008-03-31 00:00:00, 모멘텀 인덱스 : 0.620256330227285, signal : buy
날짜 : 2008-04-30 00:00:00, 모멘텀 인덱스 : 0.1625631937856451, signal : buy
날짜 : 2008-05-30 00:00:00, 모멘텀 인덱스 : 0.13725771098145367, signal : buy
날짜 : 2008-06-30 00:00:00, 모멘텀 인덱스 : 0.19310039800611611, signal : buy
날짜 : 2008-07-31 00:00:00, 모멘텀 인덱스 : -0.06633561158217971, signal :
날짜 : 2008-08-29 00:00:00, 모멘텀 인덱스 : -0.04467535754346852, signal :
날짜 : 2008-09-30 00:00:00, 모멘텀 인덱스 : -0.1324745435861613, signal :
날짜 : 2008-10-31 00:00:00, 모멘텀 인덱스 : -0.18384744399669228, signal :
날짜 : 2008-11-28 00:00:00, 모멘텀 인덱스 : -0.36793282614692635, signal :
날짜 : 2008-12-31 00:00:00, 모멘텀 인덱스 : -0.5390759773216318, signal :
날짜 : 2009-01-30 00:00:00, 모멘텀 인덱스 : -0.34002572741412074, signal :
날짜 : 2009-02-27 00:00:00, 모멘텀 인덱스 : -0.08763767507929765, signal :
날짜 : 2009-03-31 00:00:00, 모멘텀 인덱스 : -0.09130437203487918, signal :
날짜 : 2009-04-30 00:00:00, 모멘텀 인덱스 : -0.06600528040208364, signal :
날짜 : 2009-05-29 00:00:00, 모멘텀 인덱스 : -0.01347716196481874, signal :
날짜 : 2009-06-30 00:00:00, 모멘텀 인덱스 : 0.06354828682535696, signal : buy
날짜 : 2009-07-31 00:00:00, 모멘텀 인덱스 : 0.09588693193015096, signal : buy
날짜 : 2009-08-31 00:00:00, 모멘텀 인덱스 : 0.06125484621345989, signal : buy
날짜 : 2009-09-30 00:00:00, 모멘텀 인덱스 : 0.1158603596519967, signal : buy
날짜 : 2009-10-30 00:00:00, 모멘텀 인덱스 : 0.6310272141499926, signal : buy
날짜 : 2009-11-30 00:00:00, 모멘텀 인덱스 : 1.7824354851888642, signal : buy
날짜 : 2009-12-31 00:00:00, 모멘텀 인덱스 : 1.6503511437275962, signal : buy
날짜 : 2010-01-29 00:00:00, 모멘텀 인덱스 : 1.2869772866371982, signal : buy
날짜 : 2010-02-26 00:00:00, 모멘텀 인덱스 : 0.9356382476363905, signal : buy
날짜 : 2010-03-31 00:00:00, 모멘텀 인덱스 : 0.6122004190577226, signal : buy
날짜 : 2010-04-30 00:00:00, 모멘텀 인덱스 : 0.6861650404681461, signal : buy
날짜 : 2010-05-28 00:00:00, 모멘텀 인덱스 : 0.7579178037676062, signal : buy
날짜 : 2010-06-30 00:00:00, 모멘텀 인덱스 : 0.4996413220348399, signal : buy
날짜 : 2010-07-30 00:00:00, 모멘텀 인덱스 : 0.27402051599765587, signal : buy
날짜 : 2010-08-31 00:00:00, 모멘텀 인덱스 : 0.45202606350471575, signal : buy
날짜 : 2010-09-30 00:00:00, 모멘텀 인덱스 : 0.3370822693114581, signal : buy
날짜 : 2010-10-29 00:00:00, 모멘텀 인덱스 : 0.3219426028439123, signal : buy
날짜 : 2010-11-30 00:00:00, 모멘텀 인덱스 : 0.2157309332431483, signal : buy
날짜 : 2010-12-31 00:00:00, 모멘텀 인덱스 : 0.3038952481743904, signal : buy
날짜 : 2011-01-31 00:00:00, 모멘텀 인덱스 : 0.4352921956688558, signal : buy
날짜 : 2011-02-28 00:00:00, 모멘텀 인덱스 : 0.4327702376221243, signal : buy
날짜 : 2011-03-31 00:00:00, 모멘텀 인덱스 : 0.27634961990573426, signal : buy
날짜 : 2011-04-29 00:00:00, 모멘텀 인덱스 : 0.31385847641757225, signal : buy
날짜 : 2011-05-31 00:00:00, 모멘텀 인덱스 : 0.5607364862166149, signal : buy
날짜 : 2011-06-30 00:00:00, 모멘텀 인덱스 : 0.8002013399194337, signal : buy
날짜 : 2011-07-29 00:00:00, 모멘텀 인덱스 : 0.734583143053551, signal : buy
날짜 : 2011-08-31 00:00:00, 모멘텀 인덱스 : 0.7825843181513368, signal : buy
날짜 : 2011-09-30 00:00:00, 모멘텀 인덱스 : 0.37036800420690175, signal : buy
날짜 : 2011-10-31 00:00:00, 모멘텀 인덱스 : 0.3086606623170287, signal : buy
날짜 : 2011-11-30 00:00:00, 모멘텀 인덱스 : 0.2172748135897884, signal : buy
날짜 : 2011-12-30 00:00:00, 모멘텀 인덱스 : 0.06827773888888888, signal : buy
날짜 : 2012-01-31 00:00:00, 모멘텀 인덱스 : 0.02039617437158814, signal : buy
날짜 : 2012-02-29 00:00:00, 모멘텀 인덱스 : 0.12204980007125954, signal : buy
날짜 : 2012-03-30 00:00:00, 모멘텀 인덱스 : -0.0024426968732944587, signal :
날짜 : 2012-04-30 00:00:00, 모멘텀 인덱스 : 0.034216827886388135, signal : buy
날짜 : 2012-05-31 00:00:00, 모멘텀 인덱스 : 0.1790126170215811, signal : buy
날짜 : 2012-06-29 00:00:00, 모멘텀 인덱스 : 0.041175601712171606, signal : buy
날짜 : 2012-07-31 00:00:00, 모멘텀 인덱스 : 0.02619990066151545, signal : buy
날짜 : 2012-08-31 00:00:00, 모멘텀 인덱스 : 0.08395673157007355, signal : buy
날짜 : 2012-09-28 00:00:00, 모멘텀 인덱스 : 0.1481755935471598, signal : buy
날짜 : 2012-10-31 00:00:00, 모멘텀 인덱스 : 0.19113864903607913, signal : buy
날짜 : 2012-11-30 00:00:00, 모멘텀 인덱스 : 0.21113946371613834, signal : buy
날짜 : 2012-12-31 00:00:00, 모멘텀 인덱스 : 0.45609470978296796, signal : buy
날짜 : 2013-01-31 00:00:00, 모멘텀 인덱스 : 0.29021802314114353, signal : buy
날짜 : 2013-02-28 00:00:00, 모멘텀 인덱스 : 0.47754464380271977, signal : buy
날짜 : 2013-03-28 00:00:00, 모멘텀 인덱스 : 0.3049725718476266, signal : buy
날짜 : 2013-04-30 00:00:00, 모멘텀 인덱스 : 0.14915910692089107, signal : buy
날짜 : 2013-05-31 00:00:00, 모멘텀 인덱스 : 0.1920999165450208, signal : buy
날짜 : 2013-06-28 00:00:00, 모멘텀 인덱스 : 0.17889207325004408, signal : buy
날짜 : 2013-07-31 00:00:00, 모멘텀 인덱스 : 0.19027003184393432, signal : buy
날짜 : 2013-08-30 00:00:00, 모멘텀 인덱스 : 0.21327585349376332, signal : buy
날짜 : 2013-09-30 00:00:00, 모멘텀 인덱스 : 0.10482857528389422, signal : buy
날짜 : 2013-10-31 00:00:00, 모멘텀 인덱스 : 0.3424364135103972, signal : buy
날짜 : 2013-11-29 00:00:00, 모멘텀 인덱스 : 0.4442769080228892, signal : buy
날짜 : 2013-12-31 00:00:00, 모멘텀 인덱스 : 0.56901982239845, signal : buy
날짜 : 2014-01-31 00:00:00, 모멘텀 인덱스 : 0.5020339322033898, signal : buy
날짜 : 2014-02-28 00:00:00, 모멘텀 인덱스 : 0.3572861729676009, signal : buy
날짜 : 2014-03-31 00:00:00, 모멘텀 인덱스 : 0.3587752620651907, signal : buy
날짜 : 2014-04-30 00:00:00, 모멘텀 인덱스 : 0.32528268252064674, signal : buy
날짜 : 2014-05-30 00:00:00, 모멘텀 인덱스 : 0.12975479733633888, signal : buy
날짜 : 2014-06-30 00:00:00, 모멘텀 인덱스 : 0.1255356179514162, signal : buy
날짜 : 2014-07-31 00:00:00, 모멘텀 인덱스 : 0.07821525105167226, signal : buy
날짜 : 2014-08-29 00:00:00, 모멘텀 인덱스 : 0.11392261992615538, signal : buy
날짜 : 2014-09-30 00:00:00, 모멘텀 인덱스 : 0.08444214666507088, signal : buy
날짜 : 2014-10-31 00:00:00, 모멘텀 인덱스 : -0.11424881771900341, signal :
날짜 : 2014-11-28 00:00:00, 모멘텀 인덱스 : -0.22397237213521126, signal :
날짜 : 2014-12-31 00:00:00, 모멘텀 인덱스 : -0.15083124612582754, signal :
날짜 : 2015-01-30 00:00:00, 모멘텀 인덱스 : -0.1347681723227958, signal :
날짜 : 2015-02-27 00:00:00, 모멘텀 인덱스 : -0.02090584610484658, signal :
날짜 : 2015-03-31 00:00:00, 모멘텀 인덱스 : 0.13018405223688267, signal : buy
날짜 : 2015-04-30 00:00:00, 모멘텀 인덱스 : 0.22348995456729104, signal : buy
날짜 : 2015-05-29 00:00:00, 모멘텀 인덱스 : 0.3494801317989493, signal : buy
날짜 : 2015-06-30 00:00:00, 모멘텀 인덱스 : 0.32160235335181464, signal : buy
날짜 : 2015-07-31 00:00:00, 모멘텀 인덱스 : 0.3869133514461598, signal : buy
날짜 : 2015-08-31 00:00:00, 모멘텀 인덱스 : 0.5813768575023841, signal : buy
날짜 : 2015-09-30 00:00:00, 모멘텀 인덱스 : 0.5906525611546174, signal : buy
날짜 : 2015-10-30 00:00:00, 모멘텀 인덱스 : 0.6758005306167902, signal : buy
날짜 : 2015-11-30 00:00:00, 모멘텀 인덱스 : 0.8482754437628997, signal : buy
날짜 : 2015-12-31 00:00:00, 모멘텀 인덱스 : 1.1420975516269203, signal : buy
날짜 : 2016-01-29 00:00:00, 모멘텀 인덱스 : 0.9064395591527925, signal : buy
날짜 : 2016-02-29 00:00:00, 모멘텀 인덱스 : 0.5440866840899969, signal : buy
날짜 : 2016-03-31 00:00:00, 모멘텀 인덱스 : 0.48486968849981693, signal : buy
날짜 : 2016-04-29 00:00:00, 모멘텀 인덱스 : 0.4074636455200902, signal : buy
날짜 : 2016-05-31 00:00:00, 모멘텀 인덱스 : 0.5366819889022159, signal : buy
날짜 : 2016-06-30 00:00:00, 모멘텀 인덱스 : 0.665069420305185, signal : buy
날짜 : 2016-07-29 00:00:00, 모멘텀 인덱스 : 0.3347383436841924, signal : buy
날짜 : 2016-08-31 00:00:00, 모멘텀 인덱스 : 0.479478983422986, signal : buy
날짜 : 2016-09-30 00:00:00, 모멘텀 인덱스 : 0.5025883499602937, signal : buy
날짜 : 2016-10-31 00:00:00, 모멘텀 인덱스 : 0.33776955726718416, signal : buy
날짜 : 2016-11-30 00:00:00, 모멘텀 인덱스 : 0.18805659033796496, signal : buy
날짜 : 2016-12-30 00:00:00, 모멘텀 인덱스 : 0.11049133785472498, signal : buy
날짜 : 2017-01-31 00:00:00, 모멘텀 인덱스 : 0.2774616609880749, signal : buy
날짜 : 2017-02-28 00:00:00, 모멘텀 인덱스 : 0.49040749690843755, signal : buy
날짜 : 2017-03-31 00:00:00, 모멘텀 인덱스 : 0.423488910194169, signal : buy
날짜 : 2017-04-28 00:00:00, 모멘텀 인덱스 : 0.34407729303038725, signal : buy
날짜 : 2017-05-31 00:00:00, 모멘텀 인덱스 : 0.2797493298945548, signal : buy
날짜 : 2017-06-30 00:00:00, 모멘텀 인덱스 : 0.38987172235174894, signal : buy
날짜 : 2017-07-31 00:00:00, 모멘텀 인덱스 : 0.2756816628027614, signal : buy
날짜 : 2017-08-31 00:00:00, 모멘텀 인덱스 : 0.2842322321419084, signal : buy
날짜 : 2017-09-29 00:00:00, 모멘텀 인덱스 : 0.1711313352787649, signal : buy
날짜 : 2017-10-31 00:00:00, 모멘텀 인덱스 : 0.21717602425839777, signal : buy
날짜 : 2017-11-30 00:00:00, 모멘텀 인덱스 : 0.4725875250701297, signal : buy
날짜 : 2017-12-29 00:00:00, 모멘텀 인덱스 : 0.5692720176115327, signal : buy
날짜 : 2018-01-31 00:00:00, 모멘텀 인덱스 : 0.42015592291630455, signal : buy
날짜 : 2018-02-28 00:00:00, 모멘텀 인덱스 : 0.7169483725893024, signal : buy
날짜 : 2018-03-29 00:00:00, 모멘텀 인덱스 : 0.7060143800982657, signal : buy
날짜 : 2018-04-30 00:00:00, 모멘텀 인덱스 : 0.5647087878215848, signal : buy
날짜 : 2018-05-31 00:00:00, 모멘텀 인덱스 : 0.5746013682341062, signal : buy
날짜 : 2018-06-29 00:00:00, 모멘텀 인덱스 : 0.6834917303719008, signal : buy
날짜 : 2018-07-31 00:00:00, 모멘텀 인덱스 : 0.7208285236550374, signal : buy
날짜 : 2018-08-31 00:00:00, 모멘텀 인덱스 : 0.812604512036007, signal : buy
날짜 : 2018-09-28 00:00:00, 모멘텀 인덱스 : 1.0936287629345092, signal : buy
날짜 : 2018-10-31 00:00:00, 모멘텀 인덱스 : 0.812210433053975, signal : buy
날짜 : 2018-11-30 00:00:00, 모멘텀 인덱스 : 0.3579859868281283, signal : buy
날짜 : 2018-12-31 00:00:00, 모멘텀 인덱스 : 0.44524450042505626, signal : buy
날짜 : 2019-01-31 00:00:00, 모멘텀 인덱스 : 0.03520594633081142, signal : buy
날짜 : 2019-02-28 00:00:00, 모멘텀 인덱스 : 0.13638800336078027, signal : buy
날짜 : 2019-03-29 00:00:00, 모멘텀 인덱스 : 0.13299569867609118, signal : buy
날짜 : 2019-04-30 00:00:00, 모멘텀 인덱스 : 0.13703842868395855, signal : buy
날짜 : 2019-05-31 00:00:00, 모멘텀 인덱스 : 0.18218972883920692, signal : buy
날짜 : 2019-06-24 00:00:00, 모멘텀 인덱스 : 0.04428161832580346, signal : buy

In [14]:
df['trade'].value_counts()

trade
buy    4033
       1520
Name: count, dtype: int64

In [16]:
#수익율, 누적 수익율 계산
df['rtn']=1
df.head()

,Open,High,Low,Close,Adj Close,Volume,STD-YM,trade,rtn
Date,,,,,,,,,
1997-05-15,2.437500,2.500000,1.927083,1.958333,1.958333,72156000,1997-05,NaN,1
1997-05-16,1.968750,1.979167,1.708333,1.729167,1.729167,14700000,1997-05,NaN,1
1997-05-19,1.760417,1.770833,1.625000,1.708333,1.708333,6106800,1997-05,NaN,1
1997-05-20,1.729167,1.750000,1.635417,1.635417,1.635417,5467200,1997-05,NaN,1
1997-05-21,1.635417,1.645833,1.375000,1.427083,1.427083,18853200,1997-05,NaN,1

In [ ]:
for i in df.index:
    #매수 가격을 형성
    if (df.shift().loc[i,'trade']=='')  & (df.loc[i,'trade']=='buy'):
        buy = df.loc[i, 'Adj Close']
        print(f'매수일 : {i}, 매수가 : {buy}')
    # 매도 가격을 형성
    elif (df.shift().loc[i,'trade']=='buy')  & (df.loc[i,'trade']==''):
        sell = df.loc[i, 'Adj Close']
        #수익율 게산
        rtn = sell / buy
        df.loc[i,'rtn']=rtn
        print(f'매도일 : {i}, 매도가 : {sell}, 수익율 : {rtn}')

In [21]:
df['acc_rtn']=df['rtn'].cumprod()
df.tail()

,Open,High,Low,Close,Adj Close,Volume,STD-YM,trade,rtn,acc_rtn
Date,,,,,,,,,,
2019-06-18,1901.349976,1921.670044,1899.790039,1901.369995,1901.369995,3895700,2019-06,buy,1.0,86.522946
2019-06-19,1907.839966,1919.579956,1892.469971,1908.790039,1908.790039,2895300,2019-06,buy,1.0,86.522946
2019-06-20,1933.329956,1935.199951,1905.800049,1918.189941,1918.189941,3217200,2019-06,buy,1.0,86.522946
2019-06-21,1916.099976,1925.949951,1907.579956,1911.300049,1911.300049,3920300,2019-06,buy,1.0,86.522946
2019-06-24,1912.660034,1916.859985,1901.329956,1907.953857,1907.953857,1243601,2019-06,buy,1.0,86.522946

In [22]:
df.iloc[-1,-1]

np.float64(86.52294619753461)

In [23]:
#buyandhold 수익률
buy = df['Adj Close'][0]
sell=df['Adj Close'][-1]
print(sell/buy)

974.2744757914

C:\Users\user\AppData\Local\Temp\ipykernel_19092\2757622830.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  buy = df['Adj Close'][0]
C:\Users\user\AppData\Local\Temp\ipykernel_19092\2757622830.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sell=df['Adj Close'][-1]

### 절대 모멘텀 함수화
1. STD-YM 생성하는 함수
    - 매개변수
        - 데이터
        - 기준이 되는 컬럼
    - 데이터프레임을 깊은 복사
    - 컬럼에 Date가 포함되어 있는가를 확인
        - 포함되어 있다면 Date를 인덱스로 변경
    - 인덱스를 시계열 데이터로 변경
    - tz 제거
    - 데이터에서 결측치와 무한를대 제거
    - 기준이 되는 컬럼을 제외하고 모두 제거
    - STD-YM 컬럼을 생성하여 인덱스에서 년도-월 데이터를 추출한다.
    - 수정된 데이터 프레임을 되돌려준다.

In [24]:
def create_ym(_df, _col='Adj Close'):
    df=_df.copy()
    #Date가 컬럼에 포함되어 있는가?
    if 'Date' in df.columns:
        df.set_index('Date', inplace=True)
    df.index=pd.to_datetime(df.index)
    df.index=df.index.tz_localize(None)
    #결측치, 무한대 데이터 제거
    flag=df.isin([np.nan, np.inf, -np.inf]).any(axis=1)
    df=df.loc[~flag, [_col]]
    #파생 변수 STD-YM
    df['STD-YM']=df.index.strftime('%Y-%m')

    return df

In [25]:
df2=pd.read_csv('../../csv/AAPL.csv')

ym_df=create_ym(df2)
ym_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9713 entries, 1980-12-12 to 2019-06-24
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Adj Close  9713 non-null   float64
 1   STD-YM     9713 non-null   object
dtypes: float64(1), object(1)
memory usage: 227.6+ KB

In [28]:
np.nan == np.nan

False

In [29]:
np.nan in [np.nan]

True

2. 월말 데이터를 생성하여 BF1, BF2 컬럼을 생성하는 함수
    - 매개변수
        - create_ym의 결과를 받아주는 데이터
        - 시작 시간 : 2010-01-01
        - 종료 시간 : 현재 시간
        - 모멘텀 기간 : 12
        - 기준 시점 : 1 (1인 경우 월말, 0인 경우 월초)
    - 기준 시점의 값에 따라서 (월말 | 월초) 데이터만 모은 새로운 데이터 프레임을 생성
    - 생성된 데이터프레임에서 BF1 컬럼을 생성하여 전월을 데이터를 대입
    - BF2 컬럼을 생성하여 모멘텀 기간(6 : 6개월 전) 전의 데이터를 대입
    - 결측치는 0으로 대입
    - 데이터 프레임을 시작시간과 종료시간으로 데이터 필터링
    - 결과를 리턴 (월말 | 월초 데이터프레임)

In [34]:
def create_month(
    _df,
    _start='2010-01-01',
    _end=datetime.now(),
    _momentum=12,
    _last=1
):
    #_last 값에 따라서 월말, 월초
    if _last == 1:
        df = _df.groupby('STD-YM').tail(1)
    elif _last == 0:
        df = _df.groupby('STD-YM').head(1)
    else:
        return '_last의 값은 0과 1만 가능합니다.'
    #기준이 되는 컬럼의 이름을 변수로 저장
    col=_df.columns[0]
    #전월의 데이터를 BF1에 대입
    df['BF1']=df.shift(1)[col].fillna(0)
    df['BF2']=df.shift(_momentum)[col].fillna(0)

    #시작시간과 종료시간을 기준으로 데이터를 필터링
    df=df.loc[_start : _end,]
    return df

In [ ]:
month_df=create_month(ym_df, _momentum=6)
month_df.head()

3. 거래내역을 추가하고 수익을 계산하는 함수
    - 매개변수
        - ym_df가 대입이 될 수 있는 변수
        - month_df가 대입이 됳 수 있는 변수
        - 모멘텀 스코어 : 1
    - _df1을 깊은 복사 (df)
    - df에 'trade' 컬럼을 생성하여 빈 텍스트 대입
    - df에 'rtn' 컬럼을 생성하여 1을 대입
    - _df2를 이용하여 모멘텀 인덱스를 생성하고 0보다 크고 무한대가 아닌 경우에는 df에 보유 내역을 추가
    - 수익율 계산
    - 누적 수익율 계산
    - 데이터프레임과 최종 누적 수익율을 되돌려준다.

In [41]:
def create_rtn(_df1,_df2, _score=1):
    df=_df1.copy()

    df['trade']=''
    df['rtn']=1
    col=df.columns[0]

    #_df2를 이용해서 거래내역을 생성
    for i in _df2.index:
        signal=''
        #모멘텀 계산
        momentum_index=_df2.loc[i,'BF1']/_df2.loc[i,'BF2']-_score
        flag=(momentum_index > 0) & (momentum_index != np.inf)
        if flag:
            signal ='buy'

        #거래 내역 생성
        df.loc[i:, 'trade']=signal
        print(f'날짜 : {i}, 모멘텀 인덱스 : {momentum_index}, signal : {signal}')
    
    #수익율 계산
    for i in df.index:
        if (df.shift().loc[i,'trade'] == '') & (df.loc[i,'trade'] == 'buy'):
            buy=df.loc[i,col]
            print(f'매수일 : {i}, 매수가 : {buy}')
        elif (df.shift().loc[i,'trade'] == 'buy') & (df.loc[i,'trade'] == ''):
            sell = df.loc[i,col]
            rtn=sell/buy
            df.loc[i,'rtn']=rtn
            print(f'매도일 : {i}, 매도가 : {buy}, 수익율 : {rtn}')

    #누적 수익율 계산
    df['acc_rtn']=df['rtn'].cumprod()

    acc_rtn=df.iloc[-1,-1]

    return df, acc_rtn

In [ ]:
rtn_df, acc_rtn = create_rtn(ym_df,month_df, _score=1.1)

print(acc_rtn)