In [2]:
import torch                    #Tensor 데이터의 타입으로 파싱하기 위해 로드
import torch.nn as nn           #Torch안에 nn 부분만 로드하여 nn 별칭으로 사용 (nn : 기본 뼈대)
import torch.optim as optim #옵티마이저 (기울기의 변화를 주는 기능) 설치`
import pandas as pd

In [52]:
#데이터셋을 하나 생성
#독립, 종속 데이터를 Tensor로 생성
#독립변수 -> sklearn을 이용힌 ML에서는 2차원 데이터
x=torch.tensor( [ [1.0], [2.0], [3.0], [4.0] ] )
#종속 변수 -> sklearn을 이용한 ML에서는 1차원 , but torch에서는 2차원으로 생성
#종속 변수는 독립변수에서 2를 곱하고 1을 더한 값 
y=torch.tensor( [ [3.0], [5.0], [7.0], [9.0] ] )

In [53]:
type(x)

torch.Tensor

In [54]:
#sklearn에서 모델을 생성한다면 가중치가 2이고 절푠이 1인 규칙을 찾는 LinearRegression을 이용하여 예측 가능

#torch를 이용한 단순 선형 회귀
#순전파 (모델학습 -> 예측)
    #class 클래스명(부모클래스): -> 부모 클랙스의 기능 상속받아서 클래스를 선언
class LinearReg(nn.Module):

    #torch의 모든 모듈을 이용한 클래스 생성 시 2개의 함수를 필요로 선언 (생성자 함수, forward 함수)

    #생성자 함수
    def __init__(self):
        #self : 자기 자신 (클래스를 생성할 때 저장이 되는 위치)
        #super() : 부모 클래스(nn.Module)를 의미
        super(LinearReg, self).__init__()       #부모 클래스의 생성자 함수를 실행

        #선형 회귀 모델을 이용
        #nn모듈 안에 Linear() 모델은
        #첫번쨰 인자값 : 입력 데이터(독립변수)의 차원(열)의 수
        #두번째 인자값 : 출력 데이터의 차원의 수
        self.linear=nn.Linear(1,1)

    def forward(self,x):
        return self.linear(x)

In [55]:
#클래스 생성 -> 회귀 모델을 생성
model = LinearReg()

In [56]:
#손실 함수 
criterion = nn.MSELoss()

In [57]:
#옵티마이저 설정 -> 가중치를 업데이트
#어떤 모델의 파라미터를 설정할 것인가? : 첫번쪠 인자
#lr 매개변수 : 경사하강법의 보폭
optimizer=optim.SGD(model.parameters(), lr = 0.01)

In [58]:
#순점파 (생성된 모델을 호출하면 forward()함수를 호출하도록 nn.Module에서 설정이 되어 있음)
pred=model(x)
#LinearReg 클래스 안에 forward 함수를 호출하여 독립변수 x를 인자값으로 새용한다.

#손실함수
loss=criterion(pred,y)

#기울기를 초기화
optimizer.zero_grad()

#역전파 알고리즘 (자동 미분) : 데이터가 있는 쪽으로 방향을 제시한다. -> 네비게이션
loss.backward()

#가중치 업데이트 (파라미터(모델 수정))
optimizer.step()

#loss 값을 확인
print(loss)

tensor(36.8906, grad_fn=<MseLossBackward0>)

In [59]:
#DL모델은 반복 학습이 기본 설정 -> 학습 모들르 평가모드로 전환
#eval() : 모델을 평가 모드로 전환
#train() : 모델을 학습 모드로 전환
model.eval()

#에측, 평가 (메모리의 사용량을 줄이기 위해서 가중치의 계산을 잠시 비활성화)
with torch.no_grad():
    y_pred = model(x)
    loss=criterion(y_pred,y)
    print(y_pred)
    print(loss)

tensor([[1.0740],
        [1.2654],
        [1.4569],
        [1.6483]])
tensor(25.6077)

In [60]:
# 반복 학습을 통해서 가중치와 편향을 변화 시킨다. 
epochs = 200
model.train()
for epoch in range(epochs):
    # 순전파
    pred = model(x)
    # 손실 함수 
    loss = criterion(pred, y)
    # 기울기 초기화 
    optimizer.zero_grad()
    # 자동 미분(역전파) -> 가중치의 방향을 제시 
    loss.backward()
    # 가중치를 업데이트 
    optimizer.step()

    if (epoch + 1) % 20 == 0:
        # 반복횟수가 20회마다 출력 
        print(f" Epoch : [ {epoch+1}, 200 ], Loss : {round(loss.item(), 6)} ")

 Epoch : [ 20, 200 ], Loss : 0.054323
 Epoch : [ 40, 200 ], Loss : 0.026317
 Epoch : [ 60, 200 ], Loss : 0.023328
 Epoch : [ 80, 200 ], Loss : 0.020691
 Epoch : [ 100, 200 ], Loss : 0.018353
 Epoch : [ 120, 200 ], Loss : 0.016278
 Epoch : [ 140, 200 ], Loss : 0.014439
 Epoch : [ 160, 200 ], Loss : 0.012807
 Epoch : [ 180, 200 ], Loss : 0.011359
 Epoch : [ 200, 200 ], Loss : 0.010075

In [61]:
model.eval()

# 예측, 평가 ( 메모리의 사용량을 줄이기 위해서 가중치의 계산을 잠시 비활성화  )
with torch.no_grad():
    y_pred = model(x)
    loss = criterion(y_pred, y)
    print(y_pred)
    print(loss)

tensor([[3.1616],
        [5.0783],
        [6.9950],
        [8.9117]])
tensor(0.0100)

In [13]:
#1)
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
import numpy as np

In [62]:
data = fetch_california_housing()

x = data['data']
y= data['target']

print(x.shape, y.shape)

(20640, 8) (20640,)

In [65]:
#2)
import pandas as pd 
# csv 파일을 이용해서 x,y 생성 할때

df = pd.read_csv("../../data/california.csv")
df
# x = df.drop('target', axis=1).values
# y = df['target'].values

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [66]:
#1차원 데이터를 2차원으로 변경
y=y.reshape(-1,1)

In [67]:
#학습, 평가 데이터로 분할
X_train,X_test,y_train,y_test=train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [18]:
from sklearn.preprocessing import StandardScaler

In [68]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [69]:
scaler = StandardScaler()
X_train_sc = torch.tensor(scaler.fit_transform(X_train_tensor), dtype=torch.float32)
X_test_sc = torch.tensor(scaler.transform(X_test_tensor), dtype=torch.float32)

In [70]:
# 선형 회귀 모델 객체를 선언 
class Reg(nn.Module):
    # class  생성할때 입력 데이터의 피쳐의 수를 필수 인자로 설정 
    def __init__(self, _dim):
        super(Reg, self).__init__()
        self.linear = nn.Linear(_dim, 1)
    
    def forward(self, x):
        return self.linear(x)

In [71]:
# 모델을 생성 -> 생성시 입력 데이터의 피쳐의 개수를 
n_feature = X_train.shape[1]
model = Reg(n_feature)

In [72]:
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.01)

In [73]:
# 반복 실행하면서 모델에 학습하고 가중치 업데이트 
epochs = 300

for epoch in range(epochs):
    pred = model(X_train_sc)
    loss = criterion(pred, y_train_tensor)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    n = epoch + 1
    # 30회 마다 loss 확인
    if n % 30 == 0:
        print(f"Epoch : [{n} / 500], Loss : {round(loss.item(), 6)}")

Epoch : [30 / 500], Loss : 2.436301
Epoch : [60 / 500], Loss : 1.17498
Epoch : [90 / 500], Loss : 0.794715
Epoch : [120 / 500], Loss : 0.67327
Epoch : [150 / 500], Loss : 0.629799
Epoch : [180 / 500], Loss : 0.61051
Epoch : [210 / 500], Loss : 0.599172
Epoch : [240 / 500], Loss : 0.5908
Epoch : [270 / 500], Loss : 0.58381
Epoch : [300 / 500], Loss : 0.577668

In [74]:
# 학습된 모델을 이용하여 평가 검증 

model.eval()

with torch.no_grad():
    pred = model(X_test_sc)
    loss = criterion(pred, y_test_tensor)

    print(round(loss.item(), 6))

0.590146

In [75]:
for i in range(10):
    print(f"실제 데이터 : {y_test[i]}, 예측 데이터 : {pred[i].item()}")

실제 데이터 : [0.477], 예측 데이터 : 0.9358450174331665
실제 데이터 : [0.458], 예측 데이터 : 1.6135951280593872
실제 데이터 : [5.00001], 예측 데이터 : 2.3543219566345215
실제 데이터 : [2.186], 예측 데이터 : 2.7487876415252686
실제 데이터 : [2.78], 예측 데이터 : 2.3038337230682373
실제 데이터 : [1.587], 예측 데이터 : 2.1135683059692383
실제 데이터 : [1.982], 예측 데이터 : 2.710376739501953
실제 데이터 : [1.575], 예측 데이터 : 2.175811290740967
실제 데이터 : [3.4], 예측 데이터 : 2.1640427112579346
실제 데이터 : [4.466], 예측 데이터 : 4.067519187927246

In [76]:
model2 = Reg(n_feature)
criterion2 = nn.MSELoss()
optimizer2 = optim.SGD(model2.parameters(), lr = 1e-07)

In [77]:
for epoch in range(300):
    pred2 = model2(X_train_tensor)
    loss2 = criterion2(pred2, y_train_tensor)
    optimizer2.zero_grad()
    loss2.backward()
    optimizer2.step()
    n = epoch+1
    if n %30 == 0:
        print(loss2)

tensor(57.7558, grad_fn=<MseLossBackward0>)
tensor(54.9301, grad_fn=<MseLossBackward0>)
tensor(52.3150, grad_fn=<MseLossBackward0>)
tensor(49.8947, grad_fn=<MseLossBackward0>)
tensor(47.6546, grad_fn=<MseLossBackward0>)
tensor(45.5810, grad_fn=<MseLossBackward0>)
tensor(43.6614, grad_fn=<MseLossBackward0>)
tensor(41.8843, grad_fn=<MseLossBackward0>)
tensor(40.2388, grad_fn=<MseLossBackward0>)
tensor(38.7151, grad_fn=<MseLossBackward0>)

In [78]:
# 비선형 모델 생성 (선형 모델 -> 활성화 함수 -> 선형 모델 )
class Reg2(nn.Module):
    def __init__ (self, _dim):
        super(Reg2, self).__init__()
        # 다중 퍼셉트론 안에 선형 모델 -> 활성화 함수 -> 선형 모델 
        self.model = nn.Sequential(
            # 첫번째 레이어 
            nn.Linear(_dim, _dim), 
            # 활성화 함수 (비선형 구조 파악) ( Relu(일반적으로 사용), Tanh, Sigmoid )
            nn.ReLU(), 
            nn.Linear(_dim, 1)
        )
    def forward(self, x):
        return self.model(x)

In [79]:
model3 = Reg2(n_feature)
criterion3 = nn.MSELoss()
optimizer3 = optim.SGD(model3.parameters(), lr = 0.01)

In [80]:
# 반복 학습 
for epoch in range(300):
    n = epoch + 1

    pred3 = model3(X_train_sc)
    loss3 = criterion3(pred3, y_train_tensor)
    optimizer3.zero_grad()
    loss3.backward()
    optimizer3.step()

    if n % 30 == 0:
        print(f"Epoch[{n} / 300] , Loss : {round(loss3.item(), 6)} ")

Epoch[30 / 300] , Loss : 2.637828
Epoch[60 / 300] , Loss : 1.820801
Epoch[90 / 300] , Loss : 1.522667
Epoch[120 / 300] , Loss : 1.348367
Epoch[150 / 300] , Loss : 1.192755
Epoch[180 / 300] , Loss : 1.021224
Epoch[210 / 300] , Loss : 0.859193
Epoch[240 / 300] , Loss : 0.749649
Epoch[270 / 300] , Loss : 0.692656
Epoch[300 / 300] , Loss : 0.663116

In [81]:
model3.eval()
with torch.no_grad():           # 버릇처럼 사용 (메모리 최적화)
    pred3 = model3(X_test_sc)
    loss3 = criterion3(pred3, y_test_tensor)

for i in range(10):
    print(f"실제 데이터 : {y_test[i]}, 예측 데이터 : {pred3[i].item()}")

실제 데이터 : [0.477], 예측 데이터 : 1.4335846900939941
실제 데이터 : [0.458], 예측 데이터 : 1.5676791667938232
실제 데이터 : [5.00001], 예측 데이터 : 2.2060272693634033
실제 데이터 : [2.186], 예측 데이터 : 2.64737868309021
실제 데이터 : [2.78], 예측 데이터 : 2.0680367946624756
실제 데이터 : [1.587], 예측 데이터 : 1.979404330253601
실제 데이터 : [1.982], 예측 데이터 : 2.8457326889038086
실제 데이터 : [1.575], 예측 데이터 : 2.193922519683838
실제 데이터 : [3.4], 예측 데이터 : 1.9705531597137451
실제 데이터 : [4.466], 예측 데이터 : 4.136014938354492

In [82]:
#파이토치 랜덤 고정
torch.manual_seed(42)

In [34]:
#딥러닝 분류 모델
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report

In [83]:
df=pd.read_csv('../../csv/iris.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [36]:
from sklearn.preprocessing import LabelEncoder

In [84]:
#선형 모델을 이용하여 분류 -> 로지스틱 회귀와 비슷한 방식
#출력의 값이 3개의 피쳐로 출력 ()
x=df.drop('species',axis=1)
y=df['species']

In [85]:
#y의 값들을 LabelEncoder를 이용하여 숫자로 변환
le=LabelEncoder()
y=le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [86]:
#train, test 데이터 셋으로 분한
X_train,X_test,y_Train,y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
# Scaler 작업 
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc = scaler.transform(X_test)

In [88]:
# Tensor 형태로 변환 
X_train_tensor = torch.tensor(X_train_sc, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_sc, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [89]:
y_test_tensor

tensor([0, 2, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 1, 2, 0, 2, 1, 2,
        2, 1, 1, 0, 2, 0])

In [91]:
# 모델 정의 
class clf(nn.Module):
    def __init__(self, _dim):
        super(clf, self).__init__()
        self.model = nn.Linear(_dim, 3)

    def forward(self, x):
        return self.model(x)

In [92]:
clf_model = clf(x.shape[1])

In [93]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(clf_model.parameters(), lr = 0.01)

In [94]:
# for epoch in range(300):

pred = clf_model(X_train_tensor)
pred

tensor([[-8.7668e-01,  1.6183e-01, -1.1046e+00],
        [-3.1913e-01,  1.5752e-01,  4.3691e-01],
        [ 6.2556e-01, -1.8073e-01,  1.2277e+00],
        [-5.2973e-01,  8.9108e-02, -9.9331e-01],
        [-2.5389e-01, -6.5127e-03,  5.8004e-01],
        [ 4.0765e-01, -1.7411e-02,  1.3218e+00],
        [-3.5713e-02, -2.0607e-03,  5.1778e-01],
        [ 4.3783e-01, -1.1812e-01,  1.0508e+00],
        [ 1.6800e+00, -8.5004e-02,  1.9688e+00],
        [ 2.3230e+00, -2.5886e-02,  1.4476e+00],
        [ 1.4802e+00, -2.1836e-01,  2.0149e+00],
        [ 4.3371e-01,  2.6650e-02,  6.6274e-01],
        [-1.0949e+00, -1.0093e-01,  5.6715e-01],
        [-1.1919e-01, -1.3039e-01,  5.6141e-01],
        [-8.4504e-02, -6.1833e-02,  6.4350e-01],
        [-4.7429e-01,  1.6270e-01, -1.1437e+00],
        [ 3.3292e-01,  2.9840e-01, -1.4383e+00],
        [ 4.7656e-01, -2.1898e-01,  1.7175e+00],
        [ 9.1705e-01, -2.7314e-03,  9.9277e-01],
        [ 1.5869e-01,  2.0746e-01, -9.3954e-01],
        [ 1.7239e-01, -1.5824e-01,  1.2479e+00],
        [ 2.6579e-01,  2.4591e-01, -1.4259e+00],
        [ 2.3133e+00, -8.7911e-02,  1.4541e+00],
        [-5.2317e-01,  7.8278e-02, -8.2155e-01],
        [-5.0828e-01, -1.0363e-01,  5.5117e-01],
        [ 6.7892e-01, -4.8650e-02,  1.1291e+00],
        [ 6.1917e-01, -2.6781e-02,  1.2842e+00],
        [-3.0561e-02,  2.4596e-01, -1.1254e+00],
        [ 4.3398e-01,  1.9442e-01,  6.9465e-01],
        [ 2.1831e-02,  2.7135e-01, -1.2939e+00],
        [ 3.0048e-01,  3.1447e-01, -1.3438e+00],
        [ 2.9875e-01, -1.7238e-02,  6.4947e-01],
        [ 5.0515e-01, -1.6329e-02,  6.4561e-01],
        [ 1.2248e+00,  3.9410e-01, -1.6029e+00],
        [ 1.3334e+00,  6.1671e-02,  1.2682e+00],
        [ 1.4135e+00,  2.9834e-01,  6.7805e-01],
        [-2.1785e-01, -5.6967e-02,  4.4284e-01],
        [-1.3788e-01,  1.3040e-01,  2.4553e-01],
        [ 1.6499e+00,  2.4620e-01,  1.1220e+00],
        [ 8.2828e-01,  1.8202e-01,  4.7473e-01],
        [-2.6033e-01,  2.8727e-01, -1.3976e+00],
        [ 1.0952e+00, -1.0271e-01,  9.7975e-01],
        [ 6.3656e-01,  3.4805e-01, -1.3995e+00],
        [ 1.1154e+00, -2.4559e-01,  1.9259e+00],
        [-5.5552e-01,  1.1900e-01, -9.2354e-01],
        [ 6.0829e-02,  2.4445e-01, -1.2166e+00],
        [ 3.5858e-01,  7.9357e-02,  9.1907e-01],
        [-3.1074e-01,  1.7875e-01, -1.0845e+00],
        [-1.3214e+00,  6.5694e-02, -5.7155e-01],
        [-6.6164e-01,  9.3423e-02, -9.8849e-01],
        [-5.4069e-01,  1.7075e-01, -9.6385e-01],
        [ 1.9002e-01,  1.2605e-01,  2.0547e-01],
        [ 1.4473e+00,  2.5706e-01,  9.8552e-01],
        [ 8.2897e-02, -3.4020e-02,  5.6232e-01],
        [ 3.5214e-04,  2.0579e-01, -1.2289e+00],
        [ 6.2250e-01,  9.5379e-02,  7.1301e-01],
        [ 1.0950e-01,  2.1269e-02,  4.6361e-01],
        [ 1.5064e+00,  2.9628e-01,  7.9236e-01],
        [-5.0664e-01,  2.0343e-01, -1.2457e+00],
        [ 3.5858e-01,  7.9357e-02,  9.1907e-01],
        [ 1.8960e-01,  1.6728e-01, -1.0430e+00],
        [-4.3972e-01, -5.1691e-02,  7.4429e-01],
        [ 1.9423e-01,  9.9746e-02,  1.0183e+00],
        [-2.6276e-01,  1.5333e-01, -1.1813e+00],
        [ 2.6845e-01, -6.2798e-02,  9.8738e-01],
        [-2.4806e-01, -7.7876e-02,  5.8430e-01],
        [ 1.2729e+00, -3.2911e-01,  2.2442e+00],
        [ 3.4403e-01,  1.0157e-01,  3.7008e-01],
        [ 5.6239e-01, -7.5172e-02,  1.0327e+00],
        [ 1.3257e+00,  2.4082e-01,  9.2290e-01],
        [-9.9214e-02,  1.6938e-01, -1.1221e+00],
        [-2.4001e-02,  2.3513e-01, -9.5365e-01],
        [ 4.7618e-02,  2.4146e-01, -1.3637e+00],
        [-2.4995e-01, -2.0059e-01,  1.3610e+00],
        [ 1.5061e-02, -2.5422e-02,  5.3670e-01],
        [ 1.0484e+00, -2.4877e-01,  1.5454e+00],
        [-4.5445e-01, -7.8785e-02,  5.8817e-01],
        [ 1.2834e+00,  1.7022e-01,  1.2204e+00],
        [ 5.3965e-01,  2.9267e-03,  1.1206e+00],
        [ 9.5876e-01,  1.7826e-01,  2.6444e-01],
        [-4.6925e-01,  1.2777e-01, -9.8098e-01],
        [ 7.5388e-01,  2.9526e-01,  8.9856e-01],
        [-1.2539e-01, -1.5764e-01,  1.3429e+00],
        [ 1.8331e-01,  3.4588e-01, -1.1829e+00],
        [ 1.5273e+00,  1.2012e-01,  1.2848e+00],
        [ 5.3636e-01,  2.7575e-01, -1.6567e+00],
        [ 2.1302e+00,  1.9327e-01,  1.2375e+00],
        [-4.9092e-01,  1.0671e-01,  9.8089e-02],
        [ 9.2578e-01, -4.7391e-02,  9.1629e-01],
        [-5.2155e-01,  1.2703e-01, -1.0089e+00],
        [ 4.1736e-01, -4.9197e-02,  6.9402e-01],
        [ 1.2032e+00,  1.3939e-01,  8.8921e-01],
        [ 3.6679e-01,  2.8177e-01, -1.3272e+00],
        [-8.6993e-01,  2.0030e-01, -1.3257e+00],
        [ 1.4080e+00,  9.1547e-02,  1.0727e+00],
        [ 1.2552e+00, -2.8594e-01,  2.4947e+00],
        [ 1.1882e+00,  3.8341e-02,  1.3224e+00],
        [-1.0113e-01, -2.1164e-01,  1.2641e+00],
        [ 5.9357e-01,  5.2420e-02,  9.6113e-01],
        [ 6.0996e-01,  2.9276e-01, -1.3008e+00],
        [ 1.4683e+00,  1.0556e-01,  1.2815e+00],
        [ 1.9576e-01,  3.0036e-02,  4.0616e-01],
        [ 1.3419e+00, -1.5391e-01,  1.4551e+00],
        [ 1.2985e+00, -5.6194e-02,  1.5790e+00],
        [ 2.7083e-01,  2.1098e-01, -1.2632e+00],
        [ 5.0865e-01, -7.5361e-02,  7.9929e-01],
        [ 1.9171e-01, -1.5266e-01,  8.0989e-01],
        [ 2.2820e-01,  1.3962e-02,  3.1172e-01],
        [ 2.4968e-01,  7.9529e-02,  2.4673e-01],
        [ 8.8526e-01, -4.4588e-02,  8.2994e-01],
        [ 3.9350e-02,  1.7888e-01, -1.1516e+00],
        [ 8.1309e-01,  3.1669e-02,  1.3008e+00],
        [-4.8582e-01, -2.5568e-01,  1.0526e+00],
        [ 5.0093e-01,  1.0379e-01,  4.5395e-01],
        [-2.4281e-01,  1.9480e-01, -1.2553e+00],
        [-5.8507e-02,  2.1588e-01, -1.4286e+00],
        [-4.5434e-01,  2.0417e-01, -1.2177e+00],
        [ 8.3335e-01,  3.1158e-01, -1.5932e+00],
        [ 1.0038e+00, -1.0120e-01,  1.0709e+00],
        [-6.0620e-01,  1.6702e-01, -1.1389e+00]], grad_fn=<AddmmBackward0>)

In [95]:
torch.max(pred,1)

torch.return_types.max(
values=tensor([0.1618, 0.4369, 1.2277, 0.0891, 0.5800, 1.3218, 0.5178, 1.0508, 1.9688,
        2.3230, 2.0149, 0.6627, 0.5671, 0.5614, 0.6435, 0.1627, 0.3329, 1.7175,
        0.9928, 0.2075, 1.2479, 0.2658, 2.3133, 0.0783, 0.5512, 1.1291, 1.2842,
        0.2460, 0.6946, 0.2714, 0.3145, 0.6495, 0.6456, 1.2248, 1.3334, 1.4135,
        0.4428, 0.2455, 1.6499, 0.8283, 0.2873, 1.0952, 0.6366, 1.9259, 0.1190,
        0.2445, 0.9191, 0.1787, 0.0657, 0.0934, 0.1708, 0.2055, 1.4473, 0.5623,
        0.2058, 0.7130, 0.4636, 1.5064, 0.2034, 0.9191, 0.1896, 0.7443, 1.0183,
        0.1533, 0.9874, 0.5843, 2.2442, 0.3701, 1.0327, 1.3257, 0.1694, 0.2351,
        0.2415, 1.3610, 0.5367, 1.5454, 0.5882, 1.2834, 1.1206, 0.9588, 0.1278,
        0.8986, 1.3429, 0.3459, 1.5273, 0.5364, 2.1302, 0.1067, 0.9258, 0.1270,
        0.6940, 1.2032, 0.3668, 0.2003, 1.4080, 2.4947, 1.3224, 1.2641, 0.9611,
        0.6100, 1.4683, 0.4062, 1.4551, 1.5790, 0.2708, 0.7993, 0.8099, 0.3117,
        0.2497, 0.8853, 0.1789, 1.3008, 1.0526, 0.5009, 0.1948, 0.2159, 0.2042,
        0.8333, 1.0709, 0.1670], grad_fn=<MaxBackward0>),
indices=tensor([1, 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 1, 0, 2, 2, 1, 2, 0, 0, 1,
        2, 2, 2, 1, 2, 1, 1, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 2, 1, 1, 2, 1,
        1, 1, 1, 2, 0, 2, 1, 2, 2, 0, 1, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 0, 1, 1,
        1, 2, 2, 2, 2, 0, 2, 0, 1, 2, 2, 1, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 2,
        2, 2, 2, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 0, 1, 2, 2, 0, 1, 1, 1, 0, 2, 1]))

In [97]:
# 반복 학습 
clf_model.train()
for epoch in range(300):
    pred = clf_model(X_train_tensor)
    loss = criterion(pred, y_train_tensor)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    n = epoch + 1
    if n % 30 == 0:
        print(f"Epoch : [{n} / 300] , Loss : {round(loss.item(), 6)}")

ValueError: Expected input batch_size (120) to match target batch_size (16512).

In [ ]:
#평가
clf_model.eval()

with torch.no_grad():
    pred=clf_model(X_test_tensor)
    _, pred_idx = torch.max(pred, 1)

acc=accuracy_score(y_test,pred_idx)
print('정확도 : ', round(acc,4))
print(classification_report(y_test,pred_idx))

정확도 :  0.3667
              precision    recall  f1-score   support

           0       0.43      0.30      0.35        10
           1       0.00      0.00      0.00        10
           2       0.50      0.80      0.62        10

    accuracy                           0.37        30
   macro avg       0.31      0.37      0.32        30
weighted avg       0.31      0.37      0.32        30