### 분류 문제 
- 시용힐 데이터셋 : data 폴더 안에 parkinsons.csv
- 사용할 모델 : RandomForest, 다중 퍼셉트론
- 종속 변수 : status 컬럼 (0, 1)
- train : test = 8 : 2 데이터를 학습하고 검출
- 다중 퍼셉트론의 구조는 정확도가 85% 이상 (epoch의 수는 150회로 제한)
- RF는 GridsearchCV를 이용(KFold, Pipeline 활용)
    - n_esimators=50,100,200
    - max_depth : None, 10, 20
    - min_samples_split : 2, 5, 10

In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.pipeline import Pipeline
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
df=pd.read_csv('../../data/parkinsons.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              195 non-null    object
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 17  status            195 non-null    int64
 18  RPDE              195 non-null    float64
 19  DFA               195 non-null    float64
 20  spread1           195 non-null    float64
 21  spread2           195 non-null    float64
 22  D2                195 non-null    float64
 23  PPE               195 non-null    float64
dtypes: float64(22), int64(1), object(1)
memory usage: 36.7+ KB

In [3]:
df.columns

Index(['name', 'MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Jitter(%)',
       'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ', 'Jitter:DDP',
       'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'MDVP:APQ', 'Shimmer:DDA', 'NHR', 'HNR', 'status', 'RPDE', 'DFA',
       'spread1', 'spread2', 'D2', 'PPE'],
      dtype='object')

- name : 환자의 고유 번호
- MDVP:Fo(Hz) : 평균 음높이 (주파수)
- MDVP:Fhi(Hz) : 최고의 음높이
- MDVP:Flo(Hz) : 최저의 음높이
- 'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ', 'Jitter:DDP'
    - 음높이의 미세한 떨림 / 불안정성 측정
- 'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5', 'MDVP:APQ', 'Shimmer:DDA'
    - 음 소리 크기의 미세한 떨림 / 불안정성 측정
- NHR : 정상적인 소리 대비 잡음의 비율
- HNR : 잡음 대비 정상적인 소리의 비율
- RPDE : 
- DFA :
- spread1, spread2, PPE : 
- status :

In [4]:
df.head()

,name,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,phon_R01_S01_1,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,...,0.06545,0.02211,21.033,1,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,phon_R01_S01_2,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,...,0.09403,0.01929,19.085,1,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,phon_R01_S01_3,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,...,0.08270,0.01309,20.651,1,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,phon_R01_S01_4,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,...,0.08771,0.01353,20.644,1,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,phon_R01_S01_5,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,...,0.10470,0.01767,19.649,1,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335

In [5]:
#결측치의 개수
df.isna().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [6]:
df.describe()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
count,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,...,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000
mean,154.228641,197.104918,116.324631,0.006220,0.000044,0.003306,0.003446,0.009920,0.029709,0.282251,...,0.046993,0.024847,21.885974,0.753846,0.498536,0.718099,-5.684397,0.226510,2.381826,0.206552
std,41.390065,91.491548,43.521413,0.004848,0.000035,0.002968,0.002759,0.008903,0.018857,0.194877,...,0.030459,0.040418,4.425764,0.431878,0.103942,0.055336,1.090208,0.083406,0.382799,0.090119
min,88.333000,102.145000,65.476000,0.001680,0.000007,0.000680,0.000920,0.002040,0.009540,0.085000,...,0.013640,0.000650,8.441000,0.000000,0.256570,0.574282,-7.964984,0.006274,1.423287,0.044539
25%,117.572000,134.862500,84.291000,0.003460,0.000020,0.001660,0.001860,0.004985,0.016505,0.148500,...,0.024735,0.005925,19.198000,1.000000,0.421306,0.674758,-6.450096,0.174351,2.099125,0.137451
50%,148.790000,175.829000,104.315000,0.004940,0.000030,0.002500,0.002690,0.007490,0.022970,0.221000,...,0.038360,0.011660,22.085000,1.000000,0.495954,0.722254,-5.720868,0.218885,2.361532,0.194052
75%,182.769000,224.205500,140.018500,0.007365,0.000060,0.003835,0.003955,0.011505,0.037885,0.350000,...,0.060795,0.025640,25.075500,1.000000,0.587562,0.761881,-5.046192,0.279234,2.636456,0.252980
max,260.105000,592.030000,239.170000,0.033160,0.000260,0.021440,0.019580,0.064330,0.119080,1.302000,...,0.169420,0.314820,33.047000,1.000000,0.685151,0.825288,-2.434031,0.450493,3.671155,0.527367

In [7]:
x=df.drop(['name','status'],axis=1)
y=df['status']
x

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
0,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,0.426,...,0.02971,0.06545,0.02211,21.033,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,0.626,...,0.04368,0.09403,0.01929,19.085,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,0.482,...,0.03590,0.08270,0.01309,20.651,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,0.517,...,0.03772,0.08771,0.01353,20.644,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,0.584,...,0.04465,0.10470,0.01767,19.649,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,174.188,230.978,94.261,0.00459,0.00003,0.00263,0.00259,0.00790,0.04087,0.405,...,0.02745,0.07008,0.02764,19.517,0.448439,0.657899,-6.538586,0.121952,2.657476,0.133050
191,209.516,253.017,89.488,0.00564,0.00003,0.00331,0.00292,0.00994,0.02751,0.263,...,0.01879,0.04812,0.01810,19.147,0.431674,0.683244,-6.195325,0.129303,2.784312,0.168895
192,174.688,240.005,74.287,0.01360,0.00008,0.00624,0.00564,0.01873,0.02308,0.256,...,0.01667,0.03804,0.10715,17.883,0.407567,0.655683,-6.787197,0.158453,2.679772,0.131728
193,198.764,396.961,74.904,0.00740,0.00004,0.00370,0.00390,0.01109,0.02296,0.241,...,0.01588,0.03794,0.07223,19.020,0.451221,0.643956,-6.744577,0.207454,2.138608,0.123306
194,214.289,260.277,77.973,0.00567,0.00003,0.00295,0.00317,0.00885,0.01884,0.190,...,0.01373,0.03078,0.04398,21.209,0.462803,0.664357,-5.724056,0.190667,2.555477,0.148569

In [8]:
#상관계수 확인 (피쳐들 간의 상관관계를 확인하고 다중공선성의 문제를 파악)
x.corr(method='pearson')

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
MDVP:Fo(Hz),1.000000,0.400985,0.596546,-0.118003,-0.382027,-0.076194,-0.112165,-0.076213,-0.098374,-0.073742,...,-0.077774,-0.094732,-0.021981,0.059144,-0.383894,-0.446013,-0.413738,-0.249450,0.177980,-0.372356
MDVP:Fhi(Hz),0.400985,1.000000,0.084951,0.102086,-0.029198,0.097177,0.091126,0.097150,0.002281,0.043465,...,0.004937,-0.003733,0.163766,-0.024893,-0.112404,-0.343097,-0.076658,-0.002954,0.176323,-0.069543
MDVP:Flo(Hz),0.596546,0.084951,1.000000,-0.139919,-0.277815,-0.100519,-0.095828,-0.100488,-0.144543,-0.119089,...,-0.107293,-0.150737,-0.108670,0.210851,-0.400143,-0.050406,-0.394857,-0.243829,-0.100629,-0.340071
MDVP:Jitter(%),-0.118003,0.102086,-0.139919,1.000000,0.935714,0.990276,0.974256,0.990276,0.769063,0.804289,...,0.758255,0.746635,0.906959,-0.728165,0.360673,0.098572,0.693577,0.385123,0.433434,0.721543
MDVP:Jitter(Abs),-0.382027,-0.029198,-0.277815,0.935714,1.000000,0.922911,0.897778,0.922913,0.703322,0.716601,...,0.648793,0.697170,0.834972,-0.656810,0.441839,0.175036,0.735779,0.388543,0.310694,0.748162
MDVP:RAP,-0.076194,0.097177,-0.100519,0.990276,0.922911,1.000000,0.957317,1.000000,0.759581,0.790652,...,0.737455,0.744919,0.919521,-0.721543,0.342140,0.064083,0.648328,0.324407,0.426605,0.670999
MDVP:PPQ,-0.112165,0.091126,-0.095828,0.974256,0.897778,0.957317,1.000000,0.957319,0.797826,0.839239,...,0.804139,0.763592,0.844604,-0.731510,0.333274,0.196301,0.716489,0.407605,0.412524,0.769647
Jitter:DDP,-0.076213,0.097150,-0.100488,0.990276,0.922913,1.000000,0.957319,1.000000,0.759555,0.790621,...,0.737439,0.744901,0.919548,-0.721494,0.342079,0.064026,0.648328,0.324377,0.426556,0.671005
MDVP:Shimmer,-0.098374,0.002281,-0.144543,0.769063,0.703322,0.759581,0.797826,0.759555,1.000000,0.987258,...,0.950083,0.987626,0.722194,-0.835271,0.447424,0.159954,0.654734,0.452025,0.507088,0.693771
MDVP:Shimmer(dB),-0.073742,0.043465,-0.119089,0.804289,0.716601,0.790652,0.839239,0.790621,0.987258,1.000000,...,0.960977,0.963202,0.744477,-0.827805,0.410684,0.165157,0.652547,0.454314,0.512233,0.695058
Shimmer:APQ3,-0.094717,-0.003743,-0.150747,0.746625,0.697153,0.744912,0.763580,0.744894,0.987625,0.963198,...,0.896645,1.000000,0.716207,-0.827123,0.435242,0.151124,0.610967,0.402243,0.467265,0.645377
Shimmer:APQ5,-0.070682,-0.009997,-0.101095,0.725561,0.648961,0.709927,0.786780,0.709907,0.982835,0.973751,...,0.949146,0.960072,0.658080,-0.813753,0.399903,0.213873,0.646809,0.457195,0.502174,0.702456
MDVP:APQ,-0.077774,0.004937,-0.107293,0.758255,0.648793,0.737455,0.804139,0.737439,0.950083,0.960977,...,1.000000,0.896647,0.694019,-0.800407,0.451379,0.157276,0.673158,0.502188,0.536869,0.721694
Shimmer:DDA,-0.094732,-0.003733,-0.150737,0.746635,0.697170,0.744919,0.763592,0.744901,0.987626,0.963202,...,0.896647,1.000000,0.716215,-0.827130,0.435237,0.151132,0.610971,0.402223,0.467261,0.645389
NHR,-0.021981,0.163766,-0.108670,0.906959,0.834972,0.919521,0.844604,0.919548,0.722194,0.744477,...,0.694019,0.716215,1.000000,-0.714072,0.370890,-0.131882,0.540865,0.318099,0.470949,0.552591
HNR,0.059144,-0.024893,0.210851,-0.728165,-0.656810,-0.721543,-0.731510,-0.721494,-0.835271,-0.827805,...,-0.800407,-0.827130,-0.714072,1.000000,-0.598736,-0.008665,-0.673210,-0.431564,-0.601401,-0.692876
RPDE,-0.383894,-0.112404,-0.400143,0.360673,0.441839,0.342140,0.333274,0.342079,0.447424,0.410684,...,0.451379,0.435237,0.370890,-0.598736,1.000000,-0.110950,0.591117,0.479905,0.236931,0.545886
DFA,-0.446013,-0.343097,-0.050406,0.098572,0.175036,0.064083,0.196301,0.064026,0.159954,0.165157,...,0.157276,0.151132,-0.131882,-0.008665,-0.110950,1.000000,0.195668,0.166548,-0.165381,0.270445
spread1,-0.413738,-0.076658,-0.394857,0.693577,0.735779,0.648328,0.716489,0.648328,0.654734,0.652547,...,0.673158,0.610971,0.540865,-0.673210,0.591117,0.195668,1.000000,0.652358,0.495123,0.962435
spread2,-0.249450,-0.002954,-0.243829,0.385123,0.388543,0.324407,0.407605,0.324377,0.452025,0.454314,...,0.502188,0.402223,0.318099,-0.431564,0.479905,0.166548,0.652358,1.000000,0.523532,0.644711
D2,0.177980,0.176323,-0.100629,0.433434,0.310694,0.426605,0.412524,0.426556,0.507088,0.512233,...,0.536869,0.467261,0.470949,-0.601401,0.236931,-0.165381,0.495123,0.523532,1.000000,0.480585
PPE,-0.372356,-0.069543,-0.340071,0.721543,0.748162,0.670999,0.769647,0.671005,0.693771,0.695058,...,0.721694,0.645389,0.552591,-0.692876,0.545886,0.270445,0.962435,0.644711,0.480585,1.000000

In [9]:
#데이터의 분할 train, test 셋으로 분할
X_train,X_test,y_train,y_test=train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y
)

In [14]:
y.value_counts()

status
1    147
0     48
Name: count, dtype: int64

In [15]:
X_train.value_counts()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  MDVP:Shimmer(dB)  Shimmer:APQ3  Shimmer:APQ5  MDVP:APQ  Shimmer:DDA  NHR      HNR     RPDE      DFA       spread1    spread2   D2        PPE
88.333       112.240       84.072        0.00505         0.000060          0.00254   0.00330   0.00763     0.02143       0.197             0.01079       0.01342       0.01892   0.03237      0.01166  21.118  0.611137  0.776156  -5.249770  0.391002  2.407313  0.249740    1
91.904       115.871       86.292        0.00540         0.000060          0.00281   0.00336   0.00844     0.02752       0.249             0.01424       0.01641       0.02214   0.04272      0.01141  21.414  0.583390  0.792520  -4.960234  0.363566  2.642476  0.275931    1
95.056       120.103       91.226        0.00532         0.000060          0.00268   0.00332   0.00803     0.02838       0.255             0.01441       0.01725       0.02444   0.04324      0.01022  21.862  0.547037  0.798463  -5.011879  0.325996  2.432792  0.271362    1
95.385       102.145       90.264        0.00608         0.000060          0.00331   0.00332   0.00994     0.03202       0.263             0.01803       0.01886       0.02455   0.05408      0.01062  21.875  0.644954  0.779612  -5.115212  0.249494  2.017753  0.260015    1
95.605       107.715       87.549        0.00702         0.000070          0.00428   0.00371   0.01283     0.03156       0.296             0.01792       0.01841       0.02190   0.05377      0.01825  19.659  0.576084  0.778747  -5.132032  0.210458  2.232576  0.260633    1
                                                                                                                                                                                                                                                                             ..
242.852      255.034       227.911       0.00225         0.000009          0.00117   0.00139   0.00350     0.01494       0.134             0.00847       0.00879       0.01014   0.02542      0.00476  25.032  0.431285  0.638928  -6.995820  0.102083  2.365800  0.102706    1
243.439      250.912       232.435       0.00210         0.000009          0.00109   0.00137   0.00327     0.01419       0.126             0.00777       0.00898       0.01033   0.02330      0.00454  25.368  0.438296  0.635285  -7.057869  0.091608  2.330716  0.091470    1
244.990      272.210       239.170       0.00451         0.000020          0.00279   0.00237   0.00837     0.01897       0.181             0.01084       0.01121       0.01255   0.03253      0.01049  21.528  0.522812  0.646818  -7.304500  0.171088  2.095237  0.096220    1
252.455      261.487       182.786       0.00185         0.000007          0.00092   0.00113   0.00276     0.01152       0.103             0.00614       0.00730       0.00860   0.01841      0.00432  26.805  0.610367  0.635204  -7.319510  0.200873  2.028612  0.086398    1
260.105      264.919       237.303       0.00339         0.000010          0.00205   0.00186   0.00616     0.02030       0.197             0.01186       0.01230       0.01367   0.03557      0.00910  21.083  0.440988  0.628058  -7.517934  0.160414  1.881767  0.075587    1
Name: count, Length: 156, dtype: int64

In [16]:
#스케일링
scaler=StandardScaler()
X_train_sc=scaler.fit_transform(X_train)
X_test_sc=scaler.transform(X_test)

In [17]:
#torch에서 사용하기 위해 데이터의 타이을 Tensor로 변환
X_train_tensor=torch.tensor(X_train_sc,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test_sc,dtype=torch.float32)
#분류모델 에서는 종속변수 데이터의 타입을 long 타입으로 변환 (예측갑에서 최대 값의 위치와 비교하여 loss 생성)
y_train_tensor=torch.tensor(y_train.values,dtype=torch.long)
y_test_tensor=torch.tensor(y_test.values,dtype=torch.long)

In [23]:
#1번째 방법
class Clf_Model(nn.Module):
    def __init__(self, _dim):
        super(Clf_Model, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 2)
        )
    def forward(self,x):
        return self.model(x)

In [24]:
# #2번째 방법
# model = nn.Sequential(
# nn.Linear(len(X_train.columns), 64),
# nn.ReLU(),
# nn.Linear(64, 32),
# nn.ReLU(),
# nn.Linear(32, 2)
#         )

In [25]:
model=Clf_Model(X_train_tensor.shape[1])

In [28]:
criterion=nn.CrossEntropyLoss()
#Adam : 모멘텀과 lr(보폭)을 자동으로 조절해주는데 lr매개변수는 보폭의 최대 크기 설정
optimizer=optim.Adam(model.parameters(),lr=0.01)

In [29]:
#모델 학습
epochs=150

for epoch in range(epochs):
    #모델을 학습모드로 전환
    model.train()

    pred = model(X_train_tensor)
    loss = criterion(pred, y_train_tensor)

    #기울기 초기화
    optimizer.zero_grad()
    #역전파 계산
    loss.backward()
    #가중치 업데이트
    optimizer.step()
    
    if (epoch+1)%30==0:
        print(f'Epoch : [{epoch+1}/150], Loss : {round(loss.item(),6)}')

Epoch : [30/150], Loss : 0.050113
Epoch : [60/150], Loss : 0.001465
Epoch : [90/150], Loss : 0.000375
Epoch : [120/150], Loss : 0.000223
Epoch : [150/150], Loss : 0.000157

In [44]:
#예측 -> 성능 평가
model.eval()

with torch.no_grad():
    pred=model(X_test_tensor)
    #max() : (예측데이터에서 최대 값들, 최대값들의 위치)
    _, pred_labels=torch.max(pred,dim=1)
    #argmax() : 최대값들의 위치
    # pred_labels=torch.argmax(pred,dim=1)

    acc=accuracy_score(y_test_tensor,pred_labels)
    print(f'Accuracy : {round(acc,4)}')
    print(classification_report(y_test,pred_labels))

Accuracy : 0.9231
              precision    recall  f1-score   support

           0       0.82      0.90      0.86        10
           1       0.96      0.93      0.95        29

    accuracy                           0.92        39
   macro avg       0.89      0.92      0.90        39
weighted avg       0.93      0.92      0.92        39

In [39]:
# RandomForestClassifier 모델 학습 및 평가

x = df.drop(['name', 'status'], axis=1 )
y = df['status']

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y
)

# 파이프라인 생성 -> 스케일링 -> 모델에 학습 
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('rf', RandomForestClassifier(random_state=42))
])
# 폴드화 
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
# 파라미터 조합 
params ={
    'rf__n_estimators': [50, 100, 200],
    'rf__max_depth': [None, 10, 20],
    'rf__min_samples_split': [2, 5, 10]
}

grid_model = GridSearchCV(
    pipeline, 
    param_grid=params, 
    cv=cv, 
    n_jobs=-1, 
    scoring='accuracy'
)

In [40]:
grid_model.fit(X_train, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('rf',
                                        RandomForestClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'rf__max_depth': [None, 10, 20],
                         'rf__min_samples_split': [2, 5, 10],
                         'rf__n_estimators': [50, 100, 200]},
             scoring='accuracy')

In [41]:
#최적의 파라미터를 출력
print(grid_model.best_params_)

{'rf__max_depth': None, 'rf__min_samples_split': 2, 'rf__n_estimators': 200}

In [42]:
#최적의 모델을 이용하여 예측
pred=grid_model.predict(X_test)

In [43]:
rf_acc=accuracy_score(y_test,pred)
print(f'RandomForestAccuracy : {round(rf_acc,4)}')
print(classification_report(y_test,pred))

RandomForestAccuracy : 0.9231
              precision    recall  f1-score   support

           0       0.89      0.80      0.84        10
           1       0.93      0.97      0.95        29

    accuracy                           0.92        39
   macro avg       0.91      0.88      0.90        39
weighted avg       0.92      0.92      0.92        39